name: Build and Release NovaRelay

on:
  # Этот workflow будет запускаться ТОЛЬКО при отправке тега, который начинается с 'v'
  # Например: v1.0, v1.1.0, v1.2.1-alpha
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    # Предоставляем права на запись для создания релиза
    permissions:
      contents: write

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настройка Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Шаг 3: Предоставление прав на выполнение для Gradle Wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Шаг 4: Сборка исполняемого JAR-файла
    # Для релиза мы НЕ пропускаем тесты. Если тесты падают, релиз не должен состояться.
    - name: Build executable JAR with Gradle
      run: ./gradlew uberJar

    # Шаг 5: Создание релиза и загрузка JAR-файла
    # Используем популярный и надежный action softprops/action-gh-release
    - name: Create GitHub Release and Upload Artifact
      uses: softprops/action-gh-release@v2
      with:
        # Имя релиза будет "Release v1.0" (где v1.0 - это имя тега)
        name: Release ${{ github.ref_name }}
        # Тело релиза (описание). Можно оставить пустым или добавить что-то.
        body: Automated release of ${{ github.ref_name }}
        # Файлы, которые нужно прикрепить к релизу
        files: build/libs/NovaRelay.jar
