name: Build and Update Latest Release

on:
  # Запускать при каждом push в ветку main
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    name: Build and Update Release
    runs-on: ubuntu-latest

    # Предоставляем права на запись для создания/изменения релиза
    permissions:
      contents: write

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настройка Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Шаг 3: Предоставление прав на выполнение для Gradle Wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Шаг 4: Сборка исполняемого JAR-файла (с пропуском тестов)
    - name: Build executable JAR with Gradle
      run: ./gradlew uberJar -x test

    # Шаг 5: Обновление релиза "latest"
    - name: Update Latest Release
      uses: softprops/action-gh-release@v2
      with:
        # Всегда используем один и тот же тег
        tag_name: "latest" 
        # Название релиза
        name: "Latest Build (from main)"
        # Описание релиза
        body: "Это последняя сборка из ветки main. Она может быть нестабильной."
        # Файлы для загрузки
        files: build/libs/NovaRelay.jar
