name: Build NovaRelay JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настройка Java JDK 17. Ваш проект требует именно эту версию.
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Шаг 3: Предоставление прав на выполнение для Gradle Wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Шаг 4: Сборка исполняемого JAR-файла с помощью задачи uberJar
    # Эта команда создаст NovaRelay.jar со всеми зависимостями внутри.
    - name: Build executable JAR with Gradle
      run: ./gradlew uberJar

    # Шаг 5: Загрузка собранного JAR-файла как артефакта
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaRelay-JAR
        path: build/libs/NovaRelay.jar # Путь к вашему файлу
        if-no-files-found: error
